Refactor estimatedSize of table
dgraph-io/badger pull request #1524
Opened 2020-09-17 14:38 UTC by animesh2049

Users reported mismatch between size of data on disk and size reported by dgraph. Due to compression, the real size of data on disk is much smaller than what we estimate from index.EstimatedSize.

2020-09-17 14:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/badger?pullRequest=1524) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/badger?pullRequest=1524) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/badger?pullRequest=1524) it.</sub>

2020-09-18 10:50 UTC, jarifibrahim requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1524)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @animesh2049, @ashish-goswami, @jarifibrahim, and @manishrjain)

___
*[table/table.go, line 451 at r1](https://reviewable.io/reviews/dgraph-io/badger/1524#-MHRZb-e10dmQBAV4gRF:-MHRZb-f85i7YiL_w8QU:bdr5g8w) ([raw file](https://github.com/dgraph-io/badger/blob/8308a02c79be2d86ff9337895c2832e008135bf9/table/table.go#L451)):*
> ```Go
> 	// Due to compression the real size on disk is much
> 	// smaller than what we estimate from index.EstimatedSize.
> 	t.estimatedSize = uint64(t.tableSize)
> ```

This should happen only if compression is enabled. If compression is diabled, the estimated size of the file is smaller than the on-disk size.
___
*[table/table_test.go, line 927 at r2](https://reviewable.io/reviews/dgraph-io/badger/1524#-MHVp3zT8YijhZzl3bVn:-MHVp3zT8YijhZzl3bVo:b-z7noo6) ([raw file](https://github.com/dgraph-io/badger/blob/a9b078e7ef1185ac1ad5024fc6cb076039d35446/table/table_test.go#L927)):*
> ```Go
> func TestOpenKVSize(t *testing.T) {
> 	opts := getTestTableOptions()
> 	table, err := OpenTable(buildTestTable(t, "foo", 1, opts), opts)
> ```

Add a seperate test for no-compression mode


<!-- Sent from Reviewable.io -->

2020-09-18 13:37 UTC, animesh2049 reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1524)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ashish-goswami, @jarifibrahim, and @manishrjain)

___
*[table/table.go, line 451 at r1](https://reviewable.io/reviews/dgraph-io/badger/1524#-MHRZb-e10dmQBAV4gRF:-MHWQCQlA3J0cJ7IEoaB:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/8308a02c79be2d86ff9337895c2832e008135bf9/table/table.go#L451)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

This should happen only if compression is enabled. If compression is diabled, the estimated size of the file is smaller than the on-disk size.
</blockquote></details>

Done.
___
*[table/table_test.go, line 927 at r2](https://reviewable.io/reviews/dgraph-io/badger/1524#-MHVp3zT8YijhZzl3bVn:-MHWQDkVAYDk-3ktmYo-:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/a9b078e7ef1185ac1ad5024fc6cb076039d35446/table/table_test.go#L927)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Add a seperate test for no-compression mode
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-22 09:22 UTC, jarifibrahim approved these changes

2020-09-23 10:04 UTC, merged