Sourav/benchmarks
dgraph-io/badger pull request #1659
Opened 2021-02-04 15:11 UTC by souravDgraph

PTAL

2021-02-04 15:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/badger?pullRequest=1659) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/badger?pullRequest=1659) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/badger?pullRequest=1659) it.</sub>

2021-02-10 07:47 UTC, jarifibrahim requested changes
There are too many files. Let's remove all the unnecessary files.

2021-03-02 11:21 UTC, NamanJain8 reviewed
I see a few empty files. Are they needed? 
Also, is the part of the code ported from somewhere?

2021-03-02 11:46 UTC, souravDgraph commented
@NamanJain8 - Most of the code is integrated from https://github.com/cockroachdb/pebble/tree/master/cmd/pebble
The empty files are majorly the prof files generated when we run the benchmark. Since the content will be dependent on the system in which we run, so I have removed the same.

2021-03-02 14:52 UTC, NamanJain8 reviewed
Some minor comments. Generated files should not be in the codebase. Are they needed for code to run? Or they are generated when the code is run?

Also, some README would be useful for reference on how to run this benchmark etc.

2021-03-02 14:52 UTC, NamanJain8 commented on go.mod
> +	github.com/gogo/protobuf v1.3.1
Undo this version change.

2021-03-02 14:52 UTC, NamanJain8 commented on go.mod
> +	github.com/golang/snappy v0.0.2-0.20190904063534-ff6b7dc882cf
We should not use unreleased version. Maybe undo this as well.

2021-03-02 14:52 UTC, NamanJain8 commented on go.sum
> +github.com/gogo/protobuf v1.3.1/go.mod h1:SlYgWuQ5SjCEi6WLHjHCa1yvBfUnHcTbrrZtXPKa29o=
Run `go mod tidy`

2021-03-02 14:52 UTC, NamanJain8 commented on internal/manifest/testdata/version_edit_apply
> +apply
I hope we need this file. And this is not the generated one.

2021-06-26 01:49 UTC, closed without merging