chore: cherry-pick changes from main to release
dgraph-io/badger pull request #1857
Opened 2023-02-09 17:27 UTC by joshua-goldstein

Cherry picks:
#1692 
#1790 
#1701

2023-02-10 04:45 UTC, mangalaman93 requested changes

2023-02-10 04:45 UTC, mangalaman93 commented on options.go
> +//
remove the extra line

2023-02-10 04:45 UTC, mangalaman93 commented on options.go
> +// # Say VLogPercentile with 1.0 means threshold will eventually set to Options.maxValueThreshold
why # here?

2023-02-10 20:33 UTC, joshua-goldstein commented on options.go
> +//
done

2023-02-10 20:33 UTC, joshua-goldstein commented on options.go
> +// # Say VLogPercentile with 1.0 means threshold will eventually set to Options.maxValueThreshold
not sure how that got in

2023-02-11 02:21 UTC, mangalaman93 approved these changes

2023-02-11 11:34 UTC, merged