feat(txn): Add CanCommit and CanCommitAt to prevalidate commits
dgraph-io/badger pull request #1898
Opened 2023-03-02 06:05 UTC by protosam

## Problem
There is no clear way to test commits in badger without performing the commit. The `CanCommit` and `CanCommitAt` methods provide a way to test if `Commit` and `CommitAt` will work, before actually performing it. This should lend to making 2PC possible with badger in a simple way.

## Solution
The new `CanCommit` and `CanCommitAt` methods added to struct `Txn` wraps around the internal conflict checker `Txn{}.db.orc.hasConflict(txn)`, inverting it's boolean response. 

--- 
If you're reviewing this, note that I'm making an assumption about how `Txn{}.Commit()` works based. Based on [this](https://github.com/dgraph-io/badger/blob/3aa7bd6841baa884ff03f00f789317509dbcb051/managed_db.go#L73-L75), I believe that setting `Txn{}.commitTs` before running `Txn{}.Commit()` will ensure the timestamp is whatever I set it to. However, I can't seem to prove this to myself when I review the commit method.

2023-03-02 06:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/badger?pullRequest=1898) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/badger?pullRequest=1898) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/badger?pullRequest=1898) it.</sub>

2023-03-04 06:59 UTC, mangalaman93 commented
Hi there, Thanks for the PR. Could you provide us more details about your use case? Maybe point to any code which is using these functions.

2023-03-07 05:19 UTC, mangalaman93 commented
@protosam I was wondering if you are looking to use badger where you'd need these functions. I would prefer to add these functions for a use case out there instead of a made up (even when it seems logical) scenario. This will ensure that the functions are useful in at least one scenario.

2023-03-07 16:47 UTC, protosam commented
Yes, I'm actively working on an unreleased project that will be using these functions.

2023-03-08 23:53 UTC, protosam commented
As an update, this is being tested in a privately funded project. To my surprise, it seems to be working so far. It would great if it could be iterated on and contributed back to badger, but I can just maintain a fork if this doesn't seem worth-while to add upstream. Just let me know if there's a hard rejection on it.

Using Lamport clocks with `PreCommitAt` I was able to make a transaction coordinator with very little effort. The only alternative to this I could devise was maintaining what equates to being a distributed WAL (for partitioned ranges). I expect the 2PC process to require less up front cost and paralelizes better than the WAL would.

2023-03-12 05:13 UTC, mangalaman93 commented
I see, thanks for more details. I do see the value of these functions for 2 PC, though, I want to be careful adding new APIs in the library. It is easy to add more APIs and painful and change or modify them. Give me some time to think about and let me figure out what we need in order to get this change in.

2023-03-14 04:58 UTC, protosam commented
Thanks for your feedback. The use case for 2PC is pretty specific to coordinating transactions between nodes. Perhaps an assumption can be made that having this validator is only useful for managed transactions?

I think this might limit the scope to adding `PreCommitAt` and might not need all the changes that I had to add for `PreCommit`.

2023-03-18 12:43 UTC, mangalaman93 requested changes
I think what you are trying to do is decide on a commit timestamp and whether transaction can be committed or not. But txn is not written to disk until Commit or CommitAt is called. That seems reasonable I think.

I think we should test whether everything is fine in non-managed mode when PreCommit is called but Commit is not called. I want to make sure that badger is not unhappy with not finding that txn for which it has assigned a timestamp later.

2023-03-18 12:43 UTC, mangalaman93 commented on managed_db.go
> +	txn.precommitTs, txn.precommitConflict = txn.db.orc.newCommitTs(txn)
calling `newCommitTs` here is pointless because we have already set `precommitTs` and it will mostly be non zero

2023-03-20 19:40 UTC, mangalaman93 commented
I am fine with the API. I will ask other engineers to take a look at this PR too. These are the two things we need now before we can merge this change:
1. a test that does lots of writes and uses PreCommit/PreCommitAt. Discards some of the writes and Commits rest of them. Now, when we do the read, we should only find the writes that were committed and not find the writes that were only PreCommitted.
2. Cleanup the PR, and make sure you are happy with the change.

Thanks again for all the work.

2023-06-27 00:58 UTC, protosam commented
These functions don't work as intended and I'm not sure why. I ended up having to abandon this implementation and work around the issue with a group based paxos implementation.

Going to close this. The code is licenses as-is from to PR if anyone wants to use and advance it in the future for some reason.

2023-06-27 00:58 UTC, closed without merging

2023-06-27 01:26 UTC, mangalaman93 commented
@protosam could you elaborate what didn't work? An example would be very useful.