docs(README.md): add raft-badger to projects using badger
dgraph-io/badger pull request #1902
Opened 2023-03-09 02:49 UTC by rfyiamcool

add raft-badger to projects using badger

2023-03-09 05:18 UTC, mangalaman93 requested changes
Thanks for the PR.

2023-03-09 05:18 UTC, mangalaman93 commented on README.md
> +* [raft-badger](https://github.com/rfyiamcool/raft-badger) - raft-badger implements LogStore and StableStore Interface of hashcorp/raft. it is used to store raft log and metadata of hashcorp/raft.
can you also update the file docs/content/projects-using-badger/index.md. I just realized that these two are not in sync, so created a PR https://github.com/dgraph-io/badger/pull/1903/files.

2023-03-10 09:54 UTC, rfyiamcool commented
@mangalaman93  done

2023-03-10 10:01 UTC, mangalaman93 approved these changes

2023-03-10 10:21 UTC, merged