chore(changelog): update changelog for v4.1.0
dgraph-io/badger pull request #1918
Opened 2023-03-30 17:21 UTC by joshua-goldstein

Update changelog for v4.1.0.

2023-03-30 19:12 UTC, mangalaman93 requested changes

2023-03-30 19:12 UTC, mangalaman93 commented on CHANGELOG.md
> +- chore: upgrade xxhash from v1.1.0 to v2.1.2 (#1910)
This actually fixes a bug

2023-03-31 03:28 UTC, joshua-goldstein commented on CHANGELOG.md
> +- chore: upgrade xxhash from v1.1.0 to v2.1.2 (#1910)
mentioned bug

2023-03-31 03:28 UTC, joshua-goldstein commented on CHANGELOG.md
> +- chore(deps): bump golang.org/x/net from 0.0.0-20201021035429-f5854403a974 to 0.7.0 (#1885)
added cve's

2023-03-31 03:35 UTC, mangalaman93 approved these changes

2023-03-31 15:58 UTC, mangalaman93 approved these changes

2023-04-04 18:07 UTC, skrdgraph approved these changes
👍

2023-04-04 18:08 UTC, merged