docs: Add DVID as a user of Badger system
dgraph-io/badger pull request #1960
Opened 2023-06-02 20:52 UTC by DocSavage

Add DVID project as a user of the Badger embedded database.

2023-06-02 20:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/badger?pullRequest=1960) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/badger?pullRequest=1960) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/badger?pullRequest=1960) it.</sub>

2023-06-03 09:19 UTC, joshua-goldstein commented
Thanks @DocSavage .  Please sign the CLA and we can get this merged.

2023-06-03 14:46 UTC, mangalaman93 commented
Hi there, thanks for the PR. Could you also update docs/content/projects-using-badger/index.md and sign the CLA?

2023-06-05 19:13 UTC, mangalaman93 requested changes
please address my comment when you can & sign the CLA

2023-06-06 10:40 UTC, mangalaman93 approved these changes

2023-06-06 15:09 UTC, joshua-goldstein approved these changes

2023-06-06 15:09 UTC, merged