fix(aix): add aix directory synchronization support
dgraph-io/badger pull request #2115
Opened 2024-09-26 20:16 UTC by pmur

AIX doesn't support a proper flock like linux, but it seems to have enough support for process level file locking using fcntl.

For #2035

## Problem
GOOS=aix does not build. AIX does not support a linux-like flock, and does not export `unix.Flock`.

## Solution
Create an AIX specific directory-locking implementation using the AIX version of flock.

2024-09-26 20:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/badger?pullRequest=2115) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/badger?pullRequest=2115) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/badger?pullRequest=2115) it.</sub>

2024-09-26 20:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/badger?pullRequest=2115) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/badger?pullRequest=2115) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/badger?pullRequest=2115) it.</sub>

2024-10-31 21:32 UTC, pmur commented
Hi, is there something I need to fix in the CL, or is this a CI issue?

2025-01-02 14:15 UTC, pmur commented
This is still useful. Ping.

2025-02-15 00:38 UTC, ryanfoxtyler commented
@pmur tests are passing now, though I'm concerned about the maintenance cost of this when we don't have an environment to test on–is that something you're able/willing to help with?

2025-02-15 00:48 UTC, dmitshur commented
In case it's helpful, I'll point out that you can get some signal from compile-only testing via cross-compilation. For example, `GOOS=aix GOARCH=ppc64 go test -c -o=/dev/null` can be run on any platform you have access to, and at least check for build errors. (The -c flag tells the go command to compile the test binary but do not run it, while the -o flag tells it to discard the result, since you only care about the exit code.)

2025-02-17 14:50 UTC, pmur commented
I can provide some help in a limited capacity. Note, I have been using publicly available resources to implement test this (the aix golang CI instance, and the aix gcc compiler farm instance).

I hope @ayappanec might be able to provide more official help. He is part of the IBM team maintaining OSS software on aix.

2025-02-18 05:06 UTC, ayappanec commented
@pmur Thanks for tagging me here. 
We are currently in the process of creating new AIX VMs in OSU lab which we give it to various Opensource communities to enable AIX support. I will try to get a VM for this.

2025-03-19 16:33 UTC, pmur commented
ping

2026-01-21 19:39 UTC, pmur commented
This has been collected dust for awhile. Is this still blocking the transition of the Go AIX CI instance?

2026-01-21 19:47 UTC, dmitshur commented
> Is this still blocking the transition of the Go AIX CI instance?

Yeah, I re-checked https://github.com/golang/go/issues/67299#issuecomment-2285181258 and LUCI's cas dependency still fails to cross-compile for aix/ppc64 today:

```sh
$ GOOS=aix GOARCH=ppc64 CGO_ENABLED=0 go install go.chromium.org/luci/client/cmd/cas@latest
go: downloading go.chromium.org/luci v0.0.0-20260121191827-3391df2e9ccc
[...]
# github.com/dgraph-io/badger/v3
go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.2/dir_unix.go:62:13: undefined: unix.Flock
```

An alternative might be to investigate how viable or disruptive it'd be to remove the dependency on badger from its dependency tree.

2026-01-21 23:06 UTC, matthewmcneely requested changes
@pmur Sorry for the delay. If we get this through, I'll add some aix-specific build commands to our CD to validation that _at least_ it compiles without error.

2026-01-21 23:06 UTC, matthewmcneely commented on dir_aix.go
> +//go:build aix
It looks like this and the dir_unix.go are compiled for AIX. unix_dir.go doesn't specifically exclude aix, causing duplicate type/function definitions. 

```sh
$ GOOS=aix GOARCH=ppc64 go list -f '{{.GoFiles}}' .
```

shows both files in the list. Did no one get compilation errors when trying to build badger on AIX. Apologies, I don't have an aix machine on which to test...

...but running:

```sh
$ GOOS=aix GOARCH=ppc64 go build -o /dev/null  ./...
# github.com/dgraph-io/badger/v4
./dir_unix.go:23:6: directoryLockGuard redeclared in this block
        ./dir_aix.go:33:6: other declaration of directoryLockGuard
./dir_unix.go:35:6: acquireDirectoryLock redeclared in this block
        ./dir_aix.go:56:6: other declaration of acquireDirectoryLock
./dir_unix.go:52:13: undefined: unix.Flock
./dir_unix.go:70:29: cannot use f (variable of type *os.File) as string value in struct literal
./dir_unix.go:70:32: cannot use absPidFilePath (variable of type string) as bool value in struct literal
./dir_unix.go:70:48: too many values in struct literal of type directoryLockGuard
./dir_unix.go:74:34: method directoryLockGuard.release already declared at ./dir_aix.go:114:34
./dir_unix.go:81:23: guard.f undefined (type *directoryLockGuard has no field or method f)
./dir_unix.go:91:6: openDir redeclared in this block
        ./dir_aix.go:139:6: other declaration of openDir
./dir_unix.go:96:6: syncDir redeclared in this block
        ./dir_aix.go:144:6: other declaration of syncDir
./dir_unix.go:81:23: too many errors
```

2026-01-21 23:06 UTC, matthewmcneely commented on dir_aix.go
> +			fmt.Printf("error\n")
Please remove debugging line.

2026-01-21 23:06 UTC, matthewmcneely commented on dir_aix.go
> +/*
Can you replace this comment block with the new one:

```
/*
 * SPDX-FileCopyrightText: © 2017-2026 Istari Digital, Inc.
 * SPDX-License-Identifier: Apache-2.0
 */
```

2026-01-21 23:06 UTC, matthewmcneely commented on dir_aix.go
> +			lock.file.Truncate(0)
Other implementations try to Delete the file. Is this not possible? This could break code that relies on the file being deleting.

2026-01-21 23:06 UTC, matthewmcneely commented on dir_aix.go
> +var aixFlockMapLock sync.Mutex
Advisory/No change needed: contention could be optimized by conversion to a RWMutex and changing the acquire/release code below as appropriate

2026-01-21 23:06 UTC, matthewmcneely commented on dir_aix.go
> +	lock.count--
If `guard.path` is not in the map, this will panic

2026-01-21 23:06 UTC, matthewmcneely commented on dir_aix.go
> +	if err != nil {
OK, but a question: does the AIX sync actually work?

2026-01-23 16:21 UTC, pmur commented on dir_aix.go
> +//go:build aix
Ugh, I seem to have botched moving the patch from the AIX machine I wrote this on. The change to not build `dir_unix.go` for aix got lost.

2026-01-23 17:01 UTC, pmur commented on dir_aix.go
> +	if err != nil {
It may not. That's beyond my ability to test. I suspect the premise of this function is rooted in linux specific fsync behavior.

2026-01-23 21:11 UTC, pmur commented on dir_aix.go
> +	if err != nil {
And, researching a bit more. It seems a posix requirement to sync directories, however AIX just doesn't support it.

2026-01-23 21:11 UTC, pmur commented on dir_aix.go
> +	lock.count--
Fixed

2026-01-23 21:13 UTC, pmur commented on dir_aix.go
> +			lock.file.Truncate(0)
I think it should be OK to remove it.

2026-01-23 21:15 UTC, pmur commented
I suspect there is more work to get this running fully on AIX beyond implementing this. It runs, but some unit tests seem to run incredibly slow. Though, that may be related to the only machine I have access to (gcc119 in the gcc compiler farm).

2026-01-30 16:10 UTC, pmur commented
Ping

2026-01-30 18:44 UTC, matthewmcneely commented
> I suspect there is more work to get this running fully on AIX beyond implementing this

> but some unit tests seem to run incredibly slow

I'm not keen on releasing AIX support if it's half-baked and non-performant. I do not have access to a machine running AIX.

2026-01-30 19:32 UTC, pmur commented
> I'm not keen on releasing AIX support if it's half-baked and non-performant. I do not have access to a machine running AIX.

I wouldn't draw that conclusion from my N=1 sample of available machines. The community machine I have access to is slow to run *anything*; it's a shared community machine running old (power8) hardware.

The lack of directory fsync support doesn't seem like a blocker. The documentation seems to indicate it's only best effort for OS crashes (loss of power, or otherwise).

@ayappanec could you run the tests on more representative hardware? I don't trust gcc farm machine for anything performance related.

2026-02-02 04:37 UTC, ayappanec commented
@pmur Sure. Let me check and get back.

2026-02-02 14:14 UTC, ayappanec commented
Is that "jemalloc" is a prerequisite for this ? 
```
# ./test.sh
go version go1.25.5 aix/ppc64
/badger/badger /badger
github.com/dgraph-io/ristretto/v2/z
# github.com/dgraph-io/ristretto/v2/z
/go/pkg/mod/github.com/dgraph-io/ristretto/v2@v2.2.0/z/calloc_jemalloc.go:13:10: fatal error: jemalloc/jemalloc.h: No such file or directory
   13 | #include <jemalloc/jemalloc.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

2026-02-02 15:08 UTC, pmur commented
I ran the tests on gcc119 with something like `GOMAXPROCS=8 go test -v -timeout=1h`.  You could try unsetting `tags` in `test.sh` for aix and running it too.

As for jemalloc, @ayappanec you may know better. I tried building the tip of jemalloc on gcc119, it failed with a nonsensical: 
```
configure: error: Unsupported pointer size: 0
```

2026-02-02 16:23 UTC, ayappanec commented
Thanks @pmur 
Just ran `GOMAXPROCS=8 go test -v -timeout=1h`. It took around 30 minutes for completion.
```
Level Done
--- PASS: ExampleOpen (1.21s)
=== RUN   ExampleTxn_NewIterator
badger 2026/02/02 10:14:43 INFO: All 0 tables opened in 0s
badger 2026/02/02 10:14:43 INFO: Discard stats nextEmptySlot: 0
badger 2026/02/02 10:14:43 INFO: Set nextTxnTs to 0
badger 2026/02/02 10:14:43 INFO: Lifetime L0 stalled for: 0s
badger 2026/02/02 10:14:44 INFO: 
Level 0 [ ]: NumTables: 01. Size: 15 KiB of 0 B. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 64 MiB
Level 1 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 2 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 3 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 4 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 5 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 6 [B]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level Done
--- PASS: ExampleTxn_NewIterator (1.23s)
PASS
ok      github.com/dgraph-io/badger/v4  1777.993s
```

2026-02-02 17:20 UTC, matthewmcneely commented
@ayappanec Can you describe the cpu and memory characteristics for the machine on which you ran that test?

2026-02-03 05:11 UTC, ayappanec commented
```
# lparstat

System configuration: type=Shared mode=Uncapped smt=2 lcpu=30 mem=40960MB psize=17 ent=1.50 

%user  %sys  %wait  %idle physc %entc  lbusy  vcsw phint  %nsp  %utcyc
----- ----- ------ ------ ----- ----- ------ ----- ----- -----  ------
  0.1   0.3    0.0   99.7  0.01   0.5    3.3 3900039994     0   101   0.78 
```

It has 15 virtual cpus (shared mode) and smt is 2. So logical cpus is 2x15 = 30. It's a POWER8 machine
Memory is 40GB.

2026-02-04 19:41 UTC, merged

2026-03-01 21:26 UTC, francislavoie commented
https://github.com/dgraph-io/badger/issues/2035 is still open, was this meant to close it?